[pyprland]
plugins = [
  "scratchpads",
  "shortcuts_menu",
  "toggle_special",
]

[scratchpads.term]
command = "kitty --class term_dropdown"
class = "term_dropdown"
animation = "fromTop"
excludes = "*"
lazy = true
multi = false

[scratchpads.notes]
command = "kitty --class notes_dropdown fish -c noteapp"
class = "notes_dropdown"
animation = "fromLeft"
size= "40% 90%"
excludes = "*"
lazy = true
multi = false

[scratchpads.volume]
command = "pavucontrol"
animation = "fromLeft"
class = "volume_sidemenu"
size = "40% 70%"
unfocus = "hide"
excludes = "*"
lazy = true
margin = 90
multi = false

[shortcuts_menu.entries]

"Color picker" = [
    {name="format", options=["hex", "rgb", "hsv", "hsl", "cmyk"]},
    "sleep 0.2; hyprpicker --format [format] -a" # sleep to let the menu close before the picker opens
]
